version: '2'
services:
    vindo-app:
        image: vindo
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://vindo-postgresql:5432/vindo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vindo-postgresql:
        extends:
            file: postgresql.yml
            service: vindo-postgresql
